const txtAnim = document.querySelector('h2');
new Typewriter(txtAnim, {
 loop: true,
deleteSpeed:20
})
.changeDelay(20)
.typeString('<span style="color: black"<strong> je suis </strong></span>')
.pauseFor(1000)
.typeString('<span style="color: gray"<strong> Développeuse web</strong></span>')
.pause(1000)
.deleteChars(22)
.typeString('<span style="color: gray"> maitrise: </span> ')
.pauseFor(1000)
.typeString('<span style="color: #120E4D">  CSS</span> !')
.pauseFor(1000)
.deleteChars(6)
.typeString('<span style="color: #120E4D"> HTML</span> !')
.pauseFor(1000)
.deleteChars(8)
.typeString('<span style="color: #120E4D"> PHP</span> !')
.pauseFor(1000)
.deleteChars(5)
.typeString('<span style="color: #120E4D"> JavaScript</span> !')
.pauseFor(1000)
.deleteChars(13)
.typeString('<span style="color: #120E4D"> SQL/PLSQL/SQLite</span> !')
.pauseFor(1000)
.deleteChars(18)
.typeString('<span style="color: #120E4D"> git</span> !')
.pauseFor(1000)
.deleteChars(22)
.typeString('<span style="color: gray"<strong> suis  Développeuse mobile</strong><span>')
.pause(1000)
.deleteChars(25)
.typeString('<span style="color: 	#120E4D"> maitrise: Android</span> !')
.pause(100)
.deleteChars(22)
.typeString('<span style="color: gray"<strong> suis  DesignerWeb</strong><span>')
.pause(1000)
.deleteChars(18)
.typeString('<span style="color:#120E4D"> maitrise Photoshop/adobe xd</span> !')
.pause(100)
.deleteChars(29)
.typeString('<span style="color: #120E4D"> fais des maquettes</span> !')
.start()
